.TH "s_philo" 3 "Sun Feb 9 2025 14:13:06" "Philosophers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_philo
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int * \fBeat_count\fP"
.br
.ti -1c
.RI "pthread_mutex_t * \fBeat_mutex\fP"
.br
.ti -1c
.RI "int * \fBforks\fP"
.br
.ti -1c
.RI "pthread_mutex_t * \fBforks_mutex\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int * \fBlast_eat\fP"
.br
.ti -1c
.RI "int \fBnb_eat\fP"
.br
.ti -1c
.RI "size_t \fBnb_philo\fP"
.br
.ti -1c
.RI "pthread_mutex_t * \fBprint_mutex\fP"
.br
.ti -1c
.RI "int \fBtime_to_die\fP"
.br
.ti -1c
.RI "int \fBtime_to_eat\fP"
.br
.ti -1c
.RI "int \fBtime_to_sleep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBphilo\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int* eat_count"

.PP
Definition at line \fB30\fP of file \fBphilo\&.h\fP\&.
.SS "pthread_mutex_t* eat_mutex"

.PP
Definition at line \fB34\fP of file \fBphilo\&.h\fP\&.
.SS "int* forks"

.PP
Definition at line \fB29\fP of file \fBphilo\&.h\fP\&.
.SS "pthread_mutex_t* forks_mutex"

.PP
Definition at line \fB32\fP of file \fBphilo\&.h\fP\&.
.SS "int id"

.PP
Definition at line \fB23\fP of file \fBphilo\&.h\fP\&.
.SS "int* last_eat"

.PP
Definition at line \fB31\fP of file \fBphilo\&.h\fP\&.
.SS "int nb_eat"

.PP
Definition at line \fB28\fP of file \fBphilo\&.h\fP\&.
.SS "size_t nb_philo"

.PP
Definition at line \fB24\fP of file \fBphilo\&.h\fP\&.
.SS "pthread_mutex_t* print_mutex"

.PP
Definition at line \fB33\fP of file \fBphilo\&.h\fP\&.
.SS "int time_to_die"

.PP
Definition at line \fB25\fP of file \fBphilo\&.h\fP\&.
.SS "int time_to_eat"

.PP
Definition at line \fB26\fP of file \fBphilo\&.h\fP\&.
.SS "int time_to_sleep"

.PP
Definition at line \fB27\fP of file \fBphilo\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Philosophers from the source code\&.
