.TH "src Directory Reference" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBparser\fP"
.br
.ti -1c
.RI "directory \fBphilo\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdebug\-print\&.c\fP"
.br
.ti -1c
.RI "file \fBerror_message\&.c\fP"
.br
.ti -1c
.RI "file \fBft_free\&.c\fP"
.br
.ti -1c
.RI "file \fBft_init\&.c\fP"
.br
.ti -1c
.RI "file \fBft_time\&.c\fP"
.br
.ti -1c
.RI "file \fBft_time_old\&.c\fP"
.br
.ti -1c
.RI "file \fBft_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
