.TH "inc Directory Reference" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_time\&.h\fP"
.br
.ti -1c
.RI "file \fBphilo\&.h\fP"
.br
.RI "Header file for the philosopher's project\&. "
.ti -1c
.RI "file \fBroutine\&.h\fP"
.br
.in -1c
