.TH "src/philo Directory Reference" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/philo Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBphilo\-eating\&.c\fP"
.br
.ti -1c
.RI "file \fBphilo\-utils\&.c\fP"
.br
.ti -1c
.RI "file \fBphilo\&.c\fP"
.br
.in -1c
