.TH "src/debug-print.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/debug-print.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_eat\fP (\fBt_philo\fP *philo)"
.br
.RI "Just prints the number of times each philosopher has eaten\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
