.TH "src/error_message.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/error_message.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBerror_message\fP (enum \fBe_error_message\fP state)"
.br
.RI "Function to print the error message\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
