.TH "src/ft_free.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_free.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfree_philos\fP (\fBt_philo\fP *philo)"
.br
.RI "Free the philo structure\&. "
.ti -1c
.RI "void \fBfree_shared\fP (\fBt_shared\fP *shared, int count, int flag)"
.br
.RI "Free all the data in \fBs_shared\fP structure\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
