.TH "src/ft_init.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_init.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinit_philos\fP (\fBt_rules\fP *rules, \fBt_shared\fP *shared, \fBt_philo\fP **philo)"
.br
.RI "Initialize the philosophers\&. "
.ti -1c
.RI "int \fBinit_mutex\fP (\fBt_shared\fP *shared, \fBt_philo\fP *philo, int count)"
.br
.RI "Initialize the forks and mutex\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
