.TH "src/ft_time_old.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_time_old.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br
\fR#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__attribute__\fP ((__deprecated__))"
.br
.RI "Function that returns the delta time between the start_time and the current time\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "__attribute__ ((__deprecated__) )"

.PP
Function that returns the delta time between the start_time and the current time\&. 
.PP
\fBDeprecated\fP
.RS 4
not used anywhere now
.RE
.PP

.PP
\fBParameters\fP
.RS 4
\fIstart_time\fP (struct timeval) 
.RE
.PP
\fBReturns\fP
.RS 4
struct timeval 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
