.TH "src/main.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br
\fR#include 'routine\&.h'\fP
.br
\fR#include <pthread\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "Main function of the program philo\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Main function of the program philo\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP argument count 
.br
\fIargv\fP array of arguments 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 OK, otherwise error (1) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
