.TH "src/parser/parser.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parser/parser.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBparse_args\fP (int argc, char **argv, \fBt_rules\fP *rules)"
.br
.RI "Parse arguments and store them in the rules structure Uses simple atoi function to convert strings to int\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
