.TH "src/philo/philo.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/philo/philo.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br
\fR#include 'routine\&.h'\fP
.br
\fR#include 'ft_time\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBphilo_died\fP (\fBt_philo\fP *philo)"
.br
.RI "Philosopher's death that sets the is_dead flag detected by the observer\&. "
.ti -1c
.RI "int \fBphilo_routine\fP (\fBt_philo\fP *philo)"
.br
.RI "Philosopher's routine\&. "
.ti -1c
.RI "void * \fBstart_routine\fP (void *ptr)"
.br
.RI "Starting point of the philosopher's thread\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
