.TH "src/philo/philo-utils.c" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/philo/philo-utils.c
.SH SYNOPSIS
.br
.PP
\fR#include 'philo\&.h'\fP
.br
\fR#include 'routine\&.h'\fP
.br
\fR#include 'ft_time\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBis_running\fP (\fBt_philo\fP *philo)"
.br
.RI "Check if it's running\&. "
.ti -1c
.RI "int \fBhas_everyone_ate\fP (\fBt_philo\fP *philo)"
.br
.RI "Function to check if all philosophers have eaten enough\&. "
.ti -1c
.RI "void \fBprint_message\fP (\fBt_philo\fP *philo, enum \fBe_philo_state\fP p_state)"
.br
.RI "Print message for the state of the philosopher\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
