.TH "s_time" 3 "Philosopher" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_time
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <philo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBlast_meal\fP"
.br
.ti -1c
.RI "size_t \fBborn_time\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t s_time::born_time"
Time when philo started 
.SS "size_t s_time::last_meal"
Time of the last meal 

.SH "Author"
.PP 
Generated automatically by Doxygen for Philosopher from the source code\&.
